### ISSUE TITLE
BOP meeting agenda 2021

### ISSUE THREAD

**Issue by Baleja** [hackforla/BOP#196]
### Overview
This issue tracks the agenda for the BOP core team meeting and weekly roll call for projects.

Please check in on the [Roll Call Spreadsheet]() - needs to be created.

### Weekly Agenda
[March 23 2021](https://github.com/codeforamerica/brigade-playbook/issues/196#issuecomment-805145335)

**Comment by ExperimentsInHonesty** [comment]
### Tuesday 23rd March
- Make sure all new UXRs are in the CfA channel
- Deadlines for Transcriptions?
   - Getting everyone assigned and having them start so that they can ask questions
  - Ask them to monitor how long it takes them, so we can estimate completion
  - Estimate clearance of backlog based on availability

- Momentum on getting new interview issues on the board.
   - Overview of IP document needs to be fully represented on the [wiki page](https://github.com/codeforamerica/brigade-playbook/wiki/Research-Co-ordination:-Planning-your-Interviews), this [step](https://docs.google.com/document/d/1peMLcR1PvPstgctPQgVemS8bD10olch_7-Y7fxY_P58/edit) is missing
- Sanjana & Mari shadowing. 
- Planning work along sessions

**Comment by Baleja** [comment]
# Saturday 27th March
Make sure all new UXRs are in the CfA channel

- Mari Serena & david need to get together to plan the Data Organization training. run through on Tuesday? 

- Estimate clearance of backlog based on availability

- Overview of IP document needs to be fully represented on the wiki page, this step is missing
Sanjana & Mari shadowing.

Planning work along sessions

**Comment by Baleja** [comment]
Tuesday 30th March

Mari Serena to work on Research ops instructions. - Adding to the Wiki. 

Planning work along sessions.

**Comment by Baleja** [comment]
# Tuesday 6th April
- Research ops instructions, getting the sheet ready
- Understanding the data we have collected - question review.

**Comment by Baleja** [comment]
## Tuesday 20th April
- We will be discussing the preliminary Bookdown report 
- We want to answer the questions that will push CfA anfd brigades forward. 
- Discussion on presentation / visualisation of findings.

**Comment by Baleja** [comment]
#Tuesday 27th April
- define
- data organisation training run through
- proposal document outline

**Comment by Baleja** [comment]
## Tuesday 4th May

- Budget proposal: how much time should we spend on this?
- Should we have a separate link for Data Org Training?
- Research Analysis, what are the burning questions we need to answer, submit final page of contents. 
- Sierras training w/Thad

**Comment by ExperimentsInHonesty** [comment]
Starting new agenda issue for 2023-2024
